// SPEC-MANAGED: projects/rig/tech-design/semantic/source/projects-rig-src-openapi-rs.md#rust-source-unit
// CODEGEN-BEGIN
//! Generate lifecycle case skeletons from an OpenAPI 3.x spec (JSON or YAML).
//! Each operation (path x method) becomes a `[case]/[exercise]` skeleton; the
//! author fills the load knob (`n`), the body, and the expectations. OpenAPI
//! path params `{param}` become rig `{{param}}` interpolation vars served from
//! `[env]`.

use serde_json::Value;

/// One OpenAPI operation distilled to what a case skeleton needs.
/// @spec projects/rig/tech-design/semantic/source/projects-rig-src-openapi-rs.md#source
pub struct Operation {
    pub method: String,
    pub path: String,
    pub operation_id: Option<String>,
    pub summary: Option<String>,
    pub has_body: bool,
    pub success_status: u16,
}

/// Parse an OpenAPI spec (JSON or YAML) into its operations. JSON is tried
/// first; on failure the text is parsed as YAML and folded into the same
/// `serde_json::Value` shape, so both inputs share one walk.
/// @spec projects/rig/tech-design/semantic/source/projects-rig-src-openapi-rs.md#source
pub fn parse_spec(text: &str) -> Result<Vec<Operation>, String> {
    let root: Value = serde_json::from_str(text).or_else(|_| {
        serde_yaml::from_str::<Value>(text).map_err(|e| format!("not valid JSON or YAML: {e}"))
    })?;
    let paths = root
        .get("paths")
        .and_then(|p| p.as_object())
        .ok_or_else(|| "OpenAPI spec has no `paths` object".to_string())?;

    let mut ops = Vec::new();
    for (path, item) in paths {
        let Some(item_obj) = item.as_object() else {
            continue;
        };
        for method in ["get", "post", "put", "delete", "patch"] {
            let Some(op) = item_obj.get(method) else {
                continue;
            };
            ops.push(Operation {
                method: method.to_uppercase(),
                path: path.clone(),
                operation_id: op
                    .get("operationId")
                    .and_then(|v| v.as_str())
                    .map(String::from),
                summary: op.get("summary").and_then(|v| v.as_str()).map(String::from),
                has_body: op.get("requestBody").is_some(),
                success_status: first_success_status(op),
            });
        }
    }
    Ok(ops)
}

/// The smallest 2xx response code declared, defaulting to 200.
fn first_success_status(op: &Value) -> u16 {
    op.get("responses")
        .and_then(|r| r.as_object())
        .and_then(|r| {
            r.keys()
                .filter_map(|k| k.parse::<u16>().ok())
                .filter(|s| (200..300).contains(s))
                .min()
        })
        .unwrap_or(200)
}

/// snake_case case stem from an operationId, else `method_path`.
/// @spec projects/rig/tech-design/semantic/source/projects-rig-src-openapi-rs.md#source
pub fn case_stem(op: &Operation) -> String {
    let raw = op
        .operation_id
        .clone()
        .unwrap_or_else(|| format!("{}_{}", op.method.to_lowercase(), op.path));
    sanitize_ident(&raw)
}

fn sanitize_ident(s: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false; // prev source char was a lowercase letter or digit
    let mut prev_us = false;
    for c in s.chars() {
        // camelCase boundary: an uppercase after a lowercase/digit starts a word.
        if c.is_ascii_uppercase() && prev_lower {
            out.push('_');
            prev_us = false;
        }
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
            prev_lower = c.is_ascii_lowercase() || c.is_ascii_digit();
            prev_us = false;
        } else if !prev_us {
            out.push('_');
            prev_us = true;
            prev_lower = false;
        } else {
            prev_lower = false;
        }
    }
    out.trim_matches('_').to_string()
}

/// Render a lint-clean lifecycle case skeleton for one operation. OpenAPI path
/// params `{collection}` become rig `{{collection}}` vars served from `[env]`.
/// @spec projects/rig/tech-design/semantic/source/projects-rig-src-openapi-rs.md#source
pub fn render_case_skeleton(op: &Operation, suite: &str, dimension: &str) -> String {
    let stem = case_stem(op);
    let subject = op
        .summary
        .clone()
        .unwrap_or_else(|| format!("{} {}", op.method, op.path))
        .replace('"', "'");
    // OpenAPI {param} -> rig {{param}} interpolation var.
    let url_path = op.path.replace('{', "{{").replace('}', "}}");

    let mut s = String::new();
    s.push_str(
        "# Generated by `rig openapi` from an OpenAPI operation — fill n / body / expectations.\n",
    );
    s.push_str("[case]\n");
    s.push_str(&format!("id = \"{stem}\"\n"));
    s.push_str(&format!("suite = \"{suite}\"\n"));
    s.push_str(&format!("dimension = \"{dimension}\"\n"));
    s.push_str(&format!("subject = \"{subject}\"\n"));
    s.push_str("expected = \"pass\"\n");
    s.push_str("required = true\n\n");
    s.push_str("[env]\n");
    s.push_str("upstream = \"127.0.0.1:7373\"\n\n");
    s.push_str("[exercise]\n");
    s.push_str("# n = 200   # uncomment + set for a load case\n");
    s.push_str("[exercise.request]\n");
    s.push_str(&format!("method = \"{}\"\n", op.method));
    s.push_str(&format!("url = \"http://{{{{upstream}}}}{url_path}\"\n"));
    if op.has_body {
        s.push_str("body = '{}'   # fill: request body per the OpenAPI schema\n");
    }
    s.push_str("[exercise.request.expect]\n");
    s.push_str(&format!("status = {}\n\n", op.success_status));
    s.push_str("[clean]\n");
    s.push_str("delegate = \"vat-cow\"\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_json_and_yaml() {
        let json = r#"{"openapi":"3.1.0","paths":{"/search":{"post":{"operationId":"searchOp","requestBody":{},"responses":{"200":{}}}}}}"#;
        let ops = parse_spec(json).unwrap();
        assert_eq!(ops.len(), 1);
        assert_eq!(ops[0].method, "POST");
        assert_eq!(ops[0].operation_id.as_deref(), Some("searchOp"));
        assert!(ops[0].has_body);

        let yaml =
            "openapi: 3.1.0\npaths:\n  /healthz:\n    get:\n      responses:\n        '200': {}\n";
        let ops = parse_spec(yaml).unwrap();
        assert_eq!(ops.len(), 1);
        assert_eq!(ops[0].method, "GET");
        assert!(!ops[0].has_body);
    }

    #[test]
    fn no_paths_is_error() {
        assert!(parse_spec(r#"{"openapi":"3.1.0"}"#).is_err());
    }

    #[test]
    fn first_2xx_status_wins() {
        let json = r#"{"paths":{"/x":{"put":{"responses":{"500":{},"201":{},"200":{}}}}}}"#;
        let ops = parse_spec(json).unwrap();
        assert_eq!(ops[0].success_status, 200);
    }

    #[test]
    fn skeleton_converts_path_params_and_is_lint_clean() {
        let op = Operation {
            method: "POST".into(),
            path: "/collections/{collection}/search".into(),
            operation_id: Some("searchCollection".into()),
            summary: Some("search a collection".into()),
            has_body: true,
            success_status: 200,
        };
        let toml = render_case_skeleton(&op, "lumen", "api");
        assert!(toml.contains("id = \"search_collection\""));
        assert!(toml.contains("url = \"http://{{upstream}}/collections/{{collection}}/search\""));
        assert!(toml.contains("method = \"POST\""));
        assert!(toml.contains("status = 200"));
        assert!(toml.contains("body = "));
        // The generated skeleton parses + lints clean as a lifecycle case.
        let path = std::path::PathBuf::from("cases/api/search_collection.toml");
        assert!(crate::scenario::parse_case(&path, &toml).is_ok());
    }
}
// CODEGEN-END
